# Generated by Django 5.2.4 on 2025-10-14 08:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChromeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("debug_port", models.IntegerField(default=9222)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("tabs_count", models.IntegerField(default=0)),
                ("current_url", models.URLField(blank=True)),
                ("user_data_dir", models.CharField(blank=True, max_length=500)),
                ("chrome_executable", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("client_name", models.CharField(blank=True, max_length=255)),
                ("budget", models.CharField(blank=True, max_length=100)),
                ("hourly_rate", models.CharField(blank=True, max_length=100)),
                ("posted_date", models.DateTimeField()),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("job_url", models.URLField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("job_type", models.CharField(blank=True, max_length=50)),
                ("is_applied", models.BooleanField(default=False)),
                ("is_favorite", models.BooleanField(default=False)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("selector_used", models.CharField(blank=True, max_length=255)),
                ("html_snippet", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-posted_date", "-scraped_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("page_url", models.URLField()),
                ("total_jobs_found", models.IntegerField(default=0)),
                ("new_jobs_saved", models.IntegerField(default=0)),
                ("selector_used", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="running", max_length=50)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("type", models.CharField(default="info", max_length=50)),
                ("source", models.CharField(default="system", max_length=100)),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="notification_push.job",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="notification_push.scrapingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
