# Generated by Django 5.2.6 on 2025-09-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True)),
                ("budget", models.CharField(blank=True, max_length=128)),
                ("skills_required", models.CharField(blank=True, max_length=512)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=1024)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("client", models.CharField(blank=True, max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("proposal_ready", "Proposal Ready"),
                            ("accepted", "Accepted"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("cover_letter", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
