# Generated by Django 5.2.6 on 2025-09-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_skillset"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="fetch_method",
            field=models.CharField(
                blank=True, help_text="api|scrape|manual", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="fetched_at",
            field=models.DateTimeField(
                blank=True, help_text="When the source was fetched", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="saved_pdf_path",
            field=models.CharField(
                blank=True, help_text="Optional path to saved PDF", max_length=1024
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="Original source URL", max_length=1024
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tos_safe",
            field=models.BooleanField(
                default=False,
                help_text="True when ingestion follows TOS-safe/manual workflow",
            ),
        ),
    ]
