# Generated by Django 5.2.4 on 2025-10-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_fetch_method_project_fetched_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="project",
            name="is_scraped",
            field=models.BooleanField(
                default=False, help_text="True if this project came from scraping"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="scrape_source",
            field=models.CharField(
                default="manual",
                help_text="manual|logged-in-chrome|universal-dom",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="scraped_at",
            field=models.DateTimeField(
                blank=True, help_text="When this job was scraped", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="time_posted",
            field=models.CharField(
                blank=True,
                help_text='When job was posted (e.g. "1 day ago")',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("proposal_ready", "Proposal Ready"),
                    ("accepted", "Accepted"),
                    ("scraped", "Scraped"),
                ],
                default="new",
                max_length=32,
            ),
        ),
    ]
