# Generated by Django 5.2.4 on 2025-10-10 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(max_length=255, unique=True)),
                ("sender_name", models.CharField(max_length=255)),
                ("chat_url", models.URLField(blank=True)),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_messages", models.IntegerField(default=0)),
                ("unread_count", models.IntegerField(default=0)),
                ("chat_type", models.CharField(default="client", max_length=50)),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="MessageExtractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extraction_id", models.CharField(max_length=255, unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("page_url", models.URLField()),
                ("total_messages_found", models.IntegerField(default=0)),
                ("new_messages_saved", models.IntegerField(default=0)),
                ("selector_used", models.CharField(blank=True, max_length=255)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255, unique=True)),
                ("sender", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("preview", models.CharField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField()),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_from_me", models.BooleanField(default=False)),
                ("selector_used", models.CharField(blank=True, max_length=255)),
                ("html_snippet", models.TextField(blank=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="upwork_messages.chat",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("message_id", "chat")},
            },
        ),
    ]
