# Generated by Django 5.2.4 on 2025-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upwork_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_outgoing",
            field=models.BooleanField(default=False),
        ),
    ]
